apiVersion: v1
kind: Service
metadata:
  name: aceest-svc
  labels:
    app: aceest-fitness
spec:
  type: NodePort
  selector:
    app: aceest-fitness
    version: v1
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080   # reachable on http://<node-ip>:30080
